import type { Order } from "@/types/order"

export const testOrders: Order[] = [
  {
    id: "1",
    requester: "Ahmet Yılmaz",
    supplier: "GENÇTEKS",
    customer: "Diktaş Ambalaj",
    material: "OPP",
    cm: 85,
    mikron: 27,
    bobinSayisi: 2,
    description: "Şeffaf film malzemesi",
    quantity: 500,
    unit: "kg",
    createdDate: "2024-01-15",
    orderedDate: "2024-01-16",
    etaDate: "2024-01-25",
    status: "In Production",
    notes: "Acil sipariş - öncelikli üretim",
    tags: ["acil", "öncelikli"],
    pricing: {
      pricePerKg: 1.85,
      totalPrice: 925.0,
      currency: "EUR",
      priceDate: "2024-01-15",
    },
  },
  {
    id: "2",
    requester: "Mehmet Kaya",
    supplier: "GENÇTEKS",
    customer: "Beş Yıldız Plastik",
    material: "CPP",
    cm: 100,
    mikron: 30,
    bobinSayisi: 1,
    description: "Mat film malzemesi",
    quantity: 300,
    unit: "kg",
    createdDate: "2024-01-18",
    orderedDate: "2024-01-19",
    etaDate: "2024-01-28",
    status: "Ordered",
    notes: "Standart kalite yeterli",
    pricing: {
      pricePerKg: 1.7,
      totalPrice: 510.0,
      currency: "EUR",
      priceDate: "2024-01-18",
    },
  },
  {
    id: "3",
    requester: "Fatma Demir",
    supplier: "POLIMER A.Ş.",
    customer: "Mega Ambalaj",
    material: "PE",
    cm: 120,
    mikron: 50,
    bobinSayisi: 4,
    description: "Torba üretimi için hammadde",
    quantity: 1000,
    unit: "kg",
    createdDate: "2024-01-20",
    etaDate: "2024-02-05",
    status: "Requested",
    notes: "Kalite kontrolü çok önemli - numune istendi",
    tags: ["kalite-kontrol"],
    pricing: {
      pricePerKg: 1.45,
      totalPrice: 1450.0,
      currency: "EUR",
      priceDate: "2024-01-20",
    },
  },
  {
    id: "4",
    requester: "Ali Özkan",
    supplier: "GENÇTEKS",
    customer: "Diktaş Ambalaj",
    material: "OPP",
    cm: 75,
    mikron: 35,
    bobinSayisi: 1,
    description: "Kalın film malzemesi",
    quantity: 200,
    unit: "kg",
    createdDate: "2024-01-22",
    orderedDate: "2024-01-23",
    etaDate: "2024-01-30",
    deliveredDate: "2024-01-29",
    status: "Delivered",
    notes: "Zamanında teslim edildi - mükemmel kalite",
    pricing: {
      pricePerKg: 1.9,
      totalPrice: 380.0,
      currency: "EUR",
      priceDate: "2024-01-22",
    },
  },
  {
    id: "5",
    requester: "Zeynep Arslan",
    supplier: "POLIMER A.Ş.",
    customer: "Teknik Plastik",
    material: "PP",
    cm: 150,
    mikron: 80,
    bobinSayisi: 8,
    description: "Enjeksiyon kalıplama hammaddesi",
    quantity: 2000,
    unit: "kg",
    createdDate: "2024-01-25",
    orderedDate: "2024-01-26",
    etaDate: "2024-02-10",
    status: "Shipped",
    notes: "Kargo takip numarası: TR123456789",
    tags: ["kargo-takip"],
    pricing: {
      pricePerKg: 1.35,
      totalPrice: 2700.0,
      currency: "EUR",
      priceDate: "2024-01-25",
    },
  },
  {
    id: "6",
    requester: "Hasan Çelik",
    supplier: "TEKNO PLASTİK",
    customer: "Ambalaj Dünyası",
    material: "PVC",
    cm: 90,
    mikron: 25,
    bobinSayisi: 3,
    description: "Ambalaj malzemesi",
    quantity: 150,
    unit: "kg",
    createdDate: "2024-01-28",
    etaDate: "2024-02-15",
    status: "Requested",
    notes: "Fiyat teklifi bekleniyor",
  },
  {
    id: "7",
    requester: "Ayşe Yıldız",
    supplier: "GENÇTEKS",
    customer: "Etiket Pro",
    material: "BOPP",
    cm: 60,
    mikron: 20,
    bobinSayisi: 2,
    description: "Etiket üretimi malzemesi",
    quantity: 100,
    unit: "kg",
    createdDate: "2024-01-30",
    orderedDate: "2024-01-31",
    etaDate: "2024-02-08",
    status: "In Production",
    notes: "Özel baskı gerekli - tasarım onaylandı",
    tags: ["özel-baskı", "tasarım"],
    pricing: {
      pricePerKg: 2.1,
      totalPrice: 210.0,
      currency: "EUR",
      priceDate: "2024-01-30",
    },
  },
  {
    id: "8",
    requester: "Mustafa Koç",
    supplier: "POLIMER A.Ş.",
    customer: "Şişe Fabrikası",
    material: "PE",
    cm: 200,
    mikron: 100,
    bobinSayisi: 6,
    description: "Şişe üretimi hammaddesi",
    quantity: 800,
    unit: "kg",
    createdDate: "2024-02-01",
    etaDate: "2024-02-20",
    status: "Requested",
    notes: "Renk: Mavi - RAL 5015",
    tags: ["renkli"],
  },
  {
    id: "9",
    requester: "Elif Şahin",
    supplier: "TEKNO PLASTİK",
    customer: "Gıda Ambalaj",
    material: "PS",
    cm: 80,
    mikron: 15,
    bobinSayisi: 1,
    description: "Gıda kabı üretimi",
    quantity: 500,
    unit: "kg",
    createdDate: "2024-02-03",
    orderedDate: "2024-02-04",
    etaDate: "2024-02-12",
    deliveredDate: "2024-02-11",
    status: "Delivered",
    notes: "Erken teslim - müşteri çok memnun",
    pricing: {
      pricePerKg: 1.95,
      totalPrice: 975.0,
      currency: "EUR",
      priceDate: "2024-02-03",
    },
  },
  {
    id: "10",
    requester: "Oğuz Aydın",
    supplier: "GENÇTEKS",
    customer: "Laminasyon A.Ş.",
    material: "CPP",
    cm: 110,
    mikron: 40,
    bobinSayisi: 3,
    description: "Laminasyon malzemesi",
    quantity: 400,
    unit: "kg",
    createdDate: "2024-02-05",
    orderedDate: "2024-02-06",
    etaDate: "2024-01-30",
    status: "Shipped",
    notes: "GECİKMİŞ - Acil takip gerekli! Müşteri bekliyor.",
    tags: ["gecikmiş", "acil", "müşteri-bekliyor"],
    pricing: {
      pricePerKg: 1.75,
      totalPrice: 700.0,
      currency: "EUR",
      priceDate: "2024-02-05",
    },
  },
  {
    id: "11",
    requester: "Seda Bulut",
    supplier: "YENİ PLASTİK",
    customer: "İçecek Fabrikası",
    material: "PET",
    cm: 95,
    mikron: 30,
    bobinSayisi: 5,
    description: "İçecek şişesi",
    quantity: 1000,
    unit: "kg",
    createdDate: "2024-02-08",
    etaDate: "2024-02-25",
    status: "Requested",
    notes: "500ml kapasiteli - şeffaf renk",
  },
  {
    id: "12",
    requester: "Kemal Doğan",
    supplier: "TEKNO PLASTİK",
    customer: "Elektronik Kasa",
    material: "ABS",
    cm: 50,
    mikron: 60,
    bobinSayisi: 1,
    description: "Elektronik kasa malzemesi",
    quantity: 50,
    unit: "kg",
    createdDate: "2024-02-10",
    orderedDate: "2024-02-11",
    etaDate: "2024-02-18",
    status: "Ordered",
    notes: "Özel ölçü gerekli - teknik çizim gönderildi",
    tags: ["özel-ölçü", "teknik-çizim"],
    pricing: {
      pricePerKg: 2.25,
      totalPrice: 112.5,
      currency: "EUR",
      priceDate: "2024-02-10",
    },
  },
]
